### ISSUE TITLE
Group to check intl extension?

### ISSUE THREAD

**Issue by royopa** [drewm/morse-php#12]
In which group I can chech the INTL extension?
http://php.net/manual/en/intl.installation.php

**Comment by drewm** [comment]
How about `string`? Do you think it would fit there?

**Comment by royopa** [comment]
Achei que seria interessante um outro grupo relacionado a internacionalização, mas não sei se seria necessário.

**Comment by drewm** [comment]
Possibly. Which other types of tests would also go under internationalization?

**Comment by royopa** [comment]
I did a search in PHP manual and I found only intl extension to
Internationalization, so I think that it is not necessary create a new
"internationalization" group.
http://php.net/manual/en/funcref.php
Ok, I will implement intl check in string group.

On Thu, Jun 18, 2015 at 10:15 AM, Drew McLellan <notifications@github.com>
wrote:

> Possibly. Which other types of tests would also go under
> internationalization?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drewm/morse-php/issues/12#issuecomment-113151345>.
>



-- 
Rodrigo Prado de Jesus
http://about.me/royopa
royopa@gmail.com

**Comment by drewm** [comment]
Great. Thanks for your contributions!
