### ISSUE TITLE
Section to include the Ctype extension check?

### ISSUE THREAD

**Issue by royopa** [drewm/morse-php#6]
Hi
In which section I should include the extension ctype (Character type checking)?
Do you think better create a section "type-related" or include ctype in string section?

**Comment by drewm** [comment]
I think it should go into `string` as the ctype functions deal with strings.

**Comment by royopa** [comment]
Ok, I will implement this.
After this, we will have all obligatory requirements extensions to install symfony framework. (http://symfony.com/doc/current/reference/requirements.html#required)
Regards!
